const USER_ID = process.env.REACT_APP_USER_ID
const TEMPLATE_ID = process.env.REACT_APP_TEMPLATE_ID
const ACCESS_TOKEN = process.env.REACT_APP_ACCESS_TOKEN
const SERVICE_ID = process.env.REACT_APP_SERVICE_ID

export {
  USER_ID,
  TEMPLATE_ID,
  ACCESS_TOKEN,
  SERVICE_ID
}